doctrine:

    dbal:
        driver: pdo_pgsql
        host: ec2-54-146-142-58.compute-1.amazonaws.com
        dbname: d3a7vkhljas79h
        user: dafgdelcqpclss
        password: bebb6cdeaf1ddd3f43ee2cd60edc4223f1c79f92a3250a0094d30f237f65ac88
        port: 5432
        sslmode: require
        charset: utf8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
