<?php

namespace ContainerIAQISCD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediathequeControllerBenevoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Benevole\MediathequeControllerBenevole' shared autowired service.
     *
     * @return \App\Controller\Benevole\MediathequeControllerBenevole
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Benevole/MediathequeControllerBenevole.php';

        $container->services['App\\Controller\\Benevole\\MediathequeControllerBenevole'] = $instance = new \App\Controller\Benevole\MediathequeControllerBenevole();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Benevole\\MediathequeControllerBenevole', $container));

        return $instance;
    }
}
