<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKNsj7Ma\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKNsj7Ma/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKNsj7Ma.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKNsj7Ma\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKNsj7Ma\App_KernelDevDebugContainer([
    'container.build_hash' => 'KNsj7Ma',
    'container.build_id' => '01a3edab',
    'container.build_time' => 1608556086,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKNsj7Ma');
