<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRtnnWV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRtnnWV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRtnnWV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRtnnWV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRtnnWV1\App_KernelDevDebugContainer([
    'container.build_hash' => 'RtnnWV1',
    'container.build_id' => '70a69bf4',
    'container.build_time' => 1609333991,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRtnnWV1');
