<?php

namespace ContainerRZnBzTU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PYkxfO0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pYkxfO0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pYkxfO0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Articles\\LivresController::getDataFromIsbn' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\Articles\\LivresController::showAll' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\GenreController::showOneByGenre' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\Security\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\Security\\SecurityController::registration' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController::editPassword' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController::editProfil' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\Users\\UserController::addUser' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Articles\\LivresController:getDataFromIsbn' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\Articles\\LivresController:showAll' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\GenreController:showOneByGenre' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\Security\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\Security\\SecurityController:registration' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController:editPassword' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController:editProfil' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\Users\\UserController:addUser' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Articles\\LivresController::getDataFromIsbn' => '?',
            'App\\Controller\\Articles\\LivresController::showAll' => '?',
            'App\\Controller\\GenreController::showOneByGenre' => '?',
            'App\\Controller\\Security\\SecurityController::login' => '?',
            'App\\Controller\\Security\\SecurityController::registration' => '?',
            'App\\Controller\\Users\\ProfilController::editPassword' => '?',
            'App\\Controller\\Users\\ProfilController::editProfil' => '?',
            'App\\Controller\\Users\\UserController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Articles\\LivresController:getDataFromIsbn' => '?',
            'App\\Controller\\Articles\\LivresController:showAll' => '?',
            'App\\Controller\\GenreController:showOneByGenre' => '?',
            'App\\Controller\\Security\\SecurityController:login' => '?',
            'App\\Controller\\Security\\SecurityController:registration' => '?',
            'App\\Controller\\Users\\ProfilController:editPassword' => '?',
            'App\\Controller\\Users\\ProfilController:editProfil' => '?',
            'App\\Controller\\Users\\UserController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
