<?php

namespace ContainerIpQlupf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kbo06VMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kbo06VM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kbo06VM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Articles\\LivresController::clearFiltrer' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Controller\\Articles\\LivresController::getDataFromIsbn' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\Articles\\LivresController::livreDetails' => ['privates', '.service_locator.TYM6kqm', 'get_ServiceLocator_TYM6kqmService', true],
            'App\\Controller\\Articles\\LivresController::showAll' => ['privates', '.service_locator.I98JGWd', 'get_ServiceLocator_I98JGWdService', true],
            'App\\Controller\\Articles\\LivresController::transfertBDD' => ['privates', '.service_locator.a.89pYr', 'get_ServiceLocator_A_89pYrService', true],
            'App\\Controller\\Articles\\LivresController::transfertEntite' => ['privates', '.service_locator.ZCK0WRm', 'get_ServiceLocator_ZCK0WRmService', true],
            'App\\Controller\\Security\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\Security\\SecurityController::registration' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController::addFavoris' => ['privates', '.service_locator.Zr91eP6', 'get_ServiceLocator_Zr91eP6Service', true],
            'App\\Controller\\Users\\ProfilController::editPassword' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController::editProfil' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\Users\\ProfilController::favoris' => ['privates', '.service_locator.TYM6kqm', 'get_ServiceLocator_TYM6kqmService', true],
            'App\\Controller\\Users\\ProfilController::removeFavoris' => ['privates', '.service_locator.TYM6kqm', 'get_ServiceLocator_TYM6kqmService', true],
            'App\\Controller\\Users\\UserController::addUser' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Articles\\LivresController:clearFiltrer' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Controller\\Articles\\LivresController:getDataFromIsbn' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\Articles\\LivresController:livreDetails' => ['privates', '.service_locator.TYM6kqm', 'get_ServiceLocator_TYM6kqmService', true],
            'App\\Controller\\Articles\\LivresController:showAll' => ['privates', '.service_locator.I98JGWd', 'get_ServiceLocator_I98JGWdService', true],
            'App\\Controller\\Articles\\LivresController:transfertBDD' => ['privates', '.service_locator.a.89pYr', 'get_ServiceLocator_A_89pYrService', true],
            'App\\Controller\\Articles\\LivresController:transfertEntite' => ['privates', '.service_locator.ZCK0WRm', 'get_ServiceLocator_ZCK0WRmService', true],
            'App\\Controller\\Security\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\Security\\SecurityController:registration' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController:addFavoris' => ['privates', '.service_locator.Zr91eP6', 'get_ServiceLocator_Zr91eP6Service', true],
            'App\\Controller\\Users\\ProfilController:editPassword' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'App\\Controller\\Users\\ProfilController:editProfil' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\Users\\ProfilController:favoris' => ['privates', '.service_locator.TYM6kqm', 'get_ServiceLocator_TYM6kqmService', true],
            'App\\Controller\\Users\\ProfilController:removeFavoris' => ['privates', '.service_locator.TYM6kqm', 'get_ServiceLocator_TYM6kqmService', true],
            'App\\Controller\\Users\\UserController:addUser' => ['privates', '.service_locator.z0fEc8i', 'get_ServiceLocator_Z0fEc8iService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Articles\\LivresController::clearFiltrer' => '?',
            'App\\Controller\\Articles\\LivresController::getDataFromIsbn' => '?',
            'App\\Controller\\Articles\\LivresController::livreDetails' => '?',
            'App\\Controller\\Articles\\LivresController::showAll' => '?',
            'App\\Controller\\Articles\\LivresController::transfertBDD' => '?',
            'App\\Controller\\Articles\\LivresController::transfertEntite' => '?',
            'App\\Controller\\Security\\SecurityController::login' => '?',
            'App\\Controller\\Security\\SecurityController::registration' => '?',
            'App\\Controller\\Users\\ProfilController::addFavoris' => '?',
            'App\\Controller\\Users\\ProfilController::editPassword' => '?',
            'App\\Controller\\Users\\ProfilController::editProfil' => '?',
            'App\\Controller\\Users\\ProfilController::favoris' => '?',
            'App\\Controller\\Users\\ProfilController::removeFavoris' => '?',
            'App\\Controller\\Users\\UserController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Articles\\LivresController:clearFiltrer' => '?',
            'App\\Controller\\Articles\\LivresController:getDataFromIsbn' => '?',
            'App\\Controller\\Articles\\LivresController:livreDetails' => '?',
            'App\\Controller\\Articles\\LivresController:showAll' => '?',
            'App\\Controller\\Articles\\LivresController:transfertBDD' => '?',
            'App\\Controller\\Articles\\LivresController:transfertEntite' => '?',
            'App\\Controller\\Security\\SecurityController:login' => '?',
            'App\\Controller\\Security\\SecurityController:registration' => '?',
            'App\\Controller\\Users\\ProfilController:addFavoris' => '?',
            'App\\Controller\\Users\\ProfilController:editPassword' => '?',
            'App\\Controller\\Users\\ProfilController:editProfil' => '?',
            'App\\Controller\\Users\\ProfilController:favoris' => '?',
            'App\\Controller\\Users\\ProfilController:removeFavoris' => '?',
            'App\\Controller\\Users\\UserController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
