<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Genre extends \App\Entity\Genre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'idGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'libelleGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'codeGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'codeSousGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'limitAge'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'idGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'libelleGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'codeGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'codeSousGenre', '' . "\0" . 'App\\Entity\\Genre' . "\0" . 'limitAge'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Genre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdGenre(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdGenre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGenre', []);

        return parent::getIdGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleGenre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleGenre', []);

        return parent::getLibelleGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleGenre(string $libelleGenre): \App\Entity\Genre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleGenre', [$libelleGenre]);

        return parent::setLibelleGenre($libelleGenre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeGenre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeGenre', []);

        return parent::getCodeGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeGenre(string $codeGenre): \App\Entity\Genre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeGenre', [$codeGenre]);

        return parent::setCodeGenre($codeGenre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeSousGenre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeSousGenre', []);

        return parent::getCodeSousGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeSousGenre(string $codeSousGenre): \App\Entity\Genre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeSousGenre', [$codeSousGenre]);

        return parent::setCodeSousGenre($codeSousGenre);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimitAge(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimitAge', []);

        return parent::getLimitAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimitAge(int $limitAge): \App\Entity\Genre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimitAge', [$limitAge]);

        return parent::setLimitAge($limitAge);
    }

}
