<?php

namespace ContainerMIvxnoi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2YMFUe_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2YMFUe.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2YMFUe.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'br' => ['privates', 'App\\Repository\\BibliothequeRepository', 'getBibliothequeRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'br' => 'App\\Repository\\BibliothequeRepository',
            'paginator' => '?',
            'session' => '?',
        ]);
    }
}
